# Generated by Django 5.1.15 on 2026-08-26 03:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='Shield', help_text='Lucide icon name', max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(help_text='Short description or briefing')),
                ('instructions', models.TextField(help_text='Detailed markdown mission briefing')),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('INSANE', 'Insane')], db_index=True, default='EASY', max_length=20)),
                ('points', models.PositiveIntegerField(default=100, help_text='Base points awarded for first solve')),
                ('target_url', models.URLField(blank=True, help_text='Target environment sandbox URL', max_length=1000, null=True)),
                ('max_attempts', models.PositiveIntegerField(default=0, help_text='0 = unlimited attempts allowed')),
                ('time_limit_minutes', models.PositiveIntegerField(default=0, help_text='0 = no time limit')),
                ('is_paid', models.BooleanField(default=False, help_text='Restricted to paid trainees')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='PUBLISHED', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenarios', to='scenarios.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scenarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scenario',
                'verbose_name_plural': 'Scenarios',
                'db_table': 'scenarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag_value', models.CharField(help_text='e.g. CTF{secret_flag_value}', max_length=255)),
                ('is_case_sensitive', models.BooleanField(default=True)),
                ('is_regex', models.BooleanField(default=False)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='scenarios.scenario')),
            ],
            options={
                'verbose_name': 'Flag',
                'verbose_name_plural': 'Flags',
                'db_table': 'flags',
            },
        ),
        migrations.CreateModel(
            name='ScenarioFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(help_text='Supabase storage key or relative path', max_length=1000)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(default='application/pdf', max_length=100)),
                ('is_public', models.BooleanField(default=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='scenarios.scenario')),
            ],
            options={
                'verbose_name': 'Scenario File',
                'verbose_name_plural': 'Scenario Files',
                'db_table': 'scenario_files',
            },
        ),
    ]
