# Generated by Django 5.1.15 on 2026-08-30 06:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('level_value', models.PositiveIntegerField(default=10, help_text='Numeric value for sorting (e.g., 10=Easy, 20=Medium)')),
                ('color_code', models.CharField(default='emerald', help_text='Tailwind color prefix (e.g., emerald, amber, red)', max_length=50)),
            ],
            options={
                'verbose_name': 'Difficulty',
                'verbose_name_plural': 'Difficulties',
                'db_table': 'difficulties',
                'ordering': ['level_value'],
            },
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='scenario',
            name='difficulty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scenarios', to='scenarios.difficulty'),
        ),
    ]
