# Generated by Django 5.1.15 on 2026-08-26 03:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('scenarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('awarded_points', models.PositiveIntegerField(default=0)),
                ('solved_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solves', to='competitions.competition')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solves', to='scenarios.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_scenarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solved Scenario',
                'verbose_name_plural': 'Solved Scenarios',
                'db_table': 'solved_scenarios',
                'ordering': ['-solved_at'],
                'unique_together': {('user', 'scenario', 'competition')},
            },
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_score', models.PositiveIntegerField(db_index=True, default=0)),
                ('solved_count', models.PositiveIntegerField(default=0)),
                ('last_solve_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='competitions.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Score',
                'verbose_name_plural': 'User Scores',
                'db_table': 'user_scores',
                'ordering': ['-total_score', 'last_solve_time'],
                'unique_together': {('user', 'competition')},
            },
        ),
    ]
