# Generated by Django 5.1.15 on 2026-08-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_paid_access',
            field=models.BooleanField(default=False, help_text='Grants access to play paid/pro scenarios'),
        ),
    ]
