# Generated by Django 5.1.15 on 2026-08-30 07:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_totp_enabled_user_totp_secret_admininvitekey'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorUpgradeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experience_summary', models.TextField(help_text="Applicant's cybersecurity and teaching experience.")),
                ('portfolio_url', models.URLField(blank=True, help_text='Link to GitHub, LinkedIn, or personal website.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_instructor_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instructor_upgrade_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
