# Generated by Django 5.2.6 on 2026-09-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_instructorupgraderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorupgraderequest',
            name='is_seen',
            field=models.BooleanField(default=False, help_text='Indicates if the superadmin has viewed this request.'),
        ),
        migrations.AlterField(
            model_name='instructorupgraderequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', through='accounts.UserRole', through_fields=('user', 'role'), to='accounts.role'),
        ),
    ]
