# Generated by Django 5.1.15 on 2026-08-26 03:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ENDED', 'Ended')], db_index=True, default='UPCOMING', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_competitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Competition',
                'verbose_name_plural': 'Competitions',
                'db_table': 'competitions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_points', models.PositiveIntegerField(blank=True, null=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_scenarios', to='competitions.competition')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_scenarios', to='scenarios.scenario')),
            ],
            options={
                'db_table': 'competition_scenarios',
                'ordering': ['order_index'],
                'unique_together': {('competition', 'scenario')},
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='scenarios',
            field=models.ManyToManyField(blank=True, related_name='competitions', through='competitions.CompetitionScenario', to='scenarios.scenario'),
        ),
    ]
