# Generated by Django 5.1.15 on 2026-08-29 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration_minutes', models.PositiveIntegerField(default=240, help_text='Total duration of the tournament in minutes.')),
            ],
            options={
                'verbose_name': 'Tournament Config',
                'verbose_name_plural': 'Tournament Configs',
                'db_table': 'tournament_config',
            },
        ),
        migrations.CreateModel(
            name='StudentTournamentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Snapshot of duration config when the user started.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Tournament Session',
                'verbose_name_plural': 'Student Tournament Sessions',
                'db_table': 'student_tournament_sessions',
                'ordering': ['-start_time'],
            },
        ),
    ]
