# Generated by Django 5.1.15 on 2026-08-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_tournamentconfig_studenttournamentsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the tournament is active or stopped by an admin.'),
        ),
    ]
