# Generated by Django 5.1.15 on 2026-08-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_tournamentconfig_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttournamentsession',
            name='last_paused_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the tournament was paused.', null=True),
        ),
        migrations.AddField(
            model_name='studenttournamentsession',
            name='total_paused_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Total time the session was paused globally.'),
        ),
    ]
