# Generated by Django 5.1.15 on 2026-08-26 06:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=2500.0, help_text='Amount paid in PKR', max_digits=10)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Direct Bank / IBAN Transfer'), ('EASYPAISA', 'Easypaisa Mobile Account'), ('JAZZ_CASH', 'JazzCash Account'), ('RAAST', 'Raast Instant Pay'), ('OTHER', 'Other / Corporate Invoice')], default='BANK_TRANSFER', max_length=30)),
                ('sender_name', models.CharField(help_text='Name of sender account', max_length=150)),
                ('whatsapp_number', models.CharField(help_text='WhatsApp / Phone for invoice confirmation', max_length=50)),
                ('transaction_id', models.CharField(blank=True, help_text='Bank transaction or ref ID', max_length=150)),
                ('screenshot_url', models.TextField(blank=True, help_text='Storage path or URL of transaction receipt screenshot')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or requirements from trainee')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved & Access Granted'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Reason for approval/rejection')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(blank=True, help_text='Specific scenario, or leave blank for full Pro platform unlock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='scenarios.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Verification Request',
                'verbose_name_plural': 'Payment Verification Requests',
                'db_table': 'payment_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
