# Generated by Django 5.1.15 on 2026-08-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='screenshot_image',
            field=models.FileField(blank=True, help_text='Uploaded receipt image file', null=True, upload_to='payment_receipts/'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='screenshot_url',
            field=models.TextField(blank=True, help_text='External image link if provided'),
        ),
    ]
