# Generated by Django 5.1.15 on 2026-08-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentrequest_screenshot_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment Verification & Pro Inquiry', 'verbose_name_plural': 'Payment Verification & Pro Inquiries'},
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='request_type',
            field=models.CharField(choices=[('INQUIRY', 'Invoice / Bank Details Inquiry'), ('PAYMENT_PROOF', 'Payment Receipt Proof')], default='INQUIRY', help_text='Whether this is an initial bank inquiry or an uploaded payment receipt', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Reason for approval/rejection or invoice delivery note'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=2500.0, help_text='Amount in PKR', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional inquiry notes or requirements from trainee'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='sender_name',
            field=models.CharField(help_text='Name of trainee / sender account', max_length=150),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('INVOICE_SENT', 'Invoice Details Sent via WhatsApp/Email'), ('APPROVED', 'Approved & Pro Access Granted'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
