# Generated by Django 5.1.15 on 2026-08-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='is_seen',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether admin has viewed this notification'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Reason for approval/rejection or revocation note'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('INVOICE_SENT', 'Invoice Details Sent via WhatsApp/Email'), ('APPROVED', 'Approved & Pro Access Granted'), ('REVOKED', 'Pro Access Revoked / Expired'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
